# version.sh.  Generated by getversion.sh from configure.ac and git log.
SMARTMONTOOLS_PKG_VER='8.0' # package version from configure.ac
SMARTMONTOOLS_GIT_REV='65de0aee36ed' # git revision
SMARTMONTOOLS_GIT_REV_EPOCH=1784221845 # commit time (seconds since the epoch)
SMARTMONTOOLS_GIT_REV_DATE='2026-07-16' # commit date
SMARTMONTOOLS_GIT_REV_TIME='17:10:45' # commit time (UTC)
SMARTMONTOOLS_GIT_PRE_REVS=468 # commits since previous release
SMARTMONTOOLS_GIT_SVN_REV=6182 # emulated svn revision number
SMARTMONTOOLS_GIT_VER_DESC='pre-8.0-468' # version description
SMARTMONTOOLS_GIT_VER_FNAME='8.0-468-g65de0aee36ed' # version string for filenames
SMARTMONTOOLS_GIT_VER_WIN='8.0.0.468' # version for Windows VERSIONINFO
