# version.sh.  Generated by getversion.sh from configure.ac and git log.
SMARTMONTOOLS_PKG_VER='8.0' # package version from configure.ac
SMARTMONTOOLS_GIT_REV='898f5da94fb1' # git revision
SMARTMONTOOLS_GIT_REV_EPOCH=1765961334 # commit time (seconds since the epoch)
SMARTMONTOOLS_GIT_REV_DATE='2025-12-17' # commit date
SMARTMONTOOLS_GIT_REV_TIME='08:48:54' # commit time (UTC)
SMARTMONTOOLS_GIT_PRE_REVS=315 # commits since previous release
SMARTMONTOOLS_GIT_SVN_REV=6029 # emulated svn revision number
SMARTMONTOOLS_GIT_VER_DESC='pre-8.0-315' # version description
SMARTMONTOOLS_GIT_VER_FNAME='8.0-315-g898f5da94fb1' # version string for filenames
SMARTMONTOOLS_GIT_VER_WIN='8.0.0.315' # version for Windows VERSIONINFO
