# version.sh.  Generated by getversion.sh from configure.ac and git log.
SMARTMONTOOLS_PKG_VER='8.0' # package version from configure.ac
SMARTMONTOOLS_GIT_REV='c44c74b2c3dc' # git revision
SMARTMONTOOLS_GIT_REV_EPOCH=1779289248 # commit time (seconds since the epoch)
SMARTMONTOOLS_GIT_REV_DATE='2026-05-20' # commit date
SMARTMONTOOLS_GIT_REV_TIME='15:00:48' # commit time (UTC)
SMARTMONTOOLS_GIT_PRE_REVS=446 # commits since previous release
SMARTMONTOOLS_GIT_SVN_REV=6160 # emulated svn revision number
SMARTMONTOOLS_GIT_VER_DESC='pre-8.0-446' # version description
SMARTMONTOOLS_GIT_VER_FNAME='8.0-446-gc44c74b2c3dc' # version string for filenames
SMARTMONTOOLS_GIT_VER_WIN='8.0.0.446' # version for Windows VERSIONINFO
